[package]
name = "misc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures = "0.3"
sui-sdk = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
tokio = { version = "1.20", features = ["macros"] }
