[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
itertools = "0.10"
misc = { path = "../misc" }
tokio-postgres = "0.7"
log = "0.4"
tokio = { version = "1.20", features = ["macros"] }
postgres-types = { version = "*", features = ["derive"] }
