[package]
name = "tx-iterator"
version = "0.1.0"
edition = "2021"

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
anyhow = "1.0"
tokio = { version = "1.20", features = ["macros"] }
futures = "0.3"
log = "0.4"
tokio-postgres = "0.7"
itertools = "0.10"
